version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: userpassword
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  app:
    image: nextjs:latest
    container_name: nextjs_container
    ports:
      - '3000:3000'
    environment:
      - name=value
    depends_on:
      - postgres

volumes:
  postgres_data:
